#!/bin/bash
# =============================================================================
# Script 5: Open Source Manifesto Generator
# Author: Shubham Kumar | Roll No: 24BCG10078
# Course: Open Source Software | Capstone Project
# Description: Interactively collects user input and generates a personalised
#              open-source philosophy statement saved to a .txt file.
# Concepts: read, string concatenation, writing to file (>), date, aliases
# =============================================================================

# --- Alias concept demonstration ---
# Aliases allow you to create shorthand for longer commands.
# In scripts, they must be enabled explicitly with 'expand_aliases'
shopt -s expand_aliases
alias today='date +%d\ %B\ %Y'   # Alias: 'today' prints formatted date
alias current_user='whoami'       # Alias: 'current_user' returns username

# --- Output filename using alias and command substitution ---
OUTPUT="manifesto_$(current_user).txt"   # e.g., manifesto_shubham.txt

# --- Display intro banner ---
echo "============================================================"
echo "      OPEN SOURCE MANIFESTO GENERATOR — Shubham Kumar      "
echo "      Roll No: 24BCG10078 | Course: OSS Capstone           "
echo "============================================================"
echo ""
echo "  This tool generates your personal open-source philosophy"
echo "  statement based on your answers to three questions."
echo ""
echo "  Your manifesto will be saved to: $OUTPUT"
echo ""
echo "------------------------------------------------------------"
echo "  Answer the following three questions:"
echo "------------------------------------------------------------"
echo ""

# --- read: Collect interactive user input ---
# -p flag shows a prompt without a newline before input
read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""
read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

# --- Validate inputs — ensure user didn't leave fields blank ---
# If any field is empty, assign a default value
if [ -z "$TOOL" ]; then
    TOOL="Python"        # Default tool
fi
if [ -z "$FREEDOM" ]; then
    FREEDOM="choice"     # Default freedom word
fi
if [ -z "$BUILD" ]; then
    BUILD="a learning platform"   # Default build idea
fi

# --- Date using alias ---
DATE=$(today)

# --- String concatenation to build the manifesto ---
# Each paragraph is built by joining variables with descriptive text
PARA1="I, Shubham Kumar (24BCG10078), believe in the power of open source."
PARA1="$PARA1 Every day, I use $TOOL — a tool built not by a corporation, but by"
PARA1="$PARA1 a community of people who chose to share their work with the world."
PARA1="$PARA1 That choice changed everything."

PARA2="To me, freedom in software means $FREEDOM — the ability to look inside the tools"
PARA2="$PARA2 I depend on, understand them, improve them, and pass them on."
PARA2="$PARA2 This is what the Python Software Foundation License guarantees:"
PARA2="$PARA2 not just the right to use Python, but the right to understand it."

PARA3="One day, I will build $BUILD and release it openly, because I have"
PARA3="$PARA3 benefited from the generosity of open-source builders before me."
PARA3="$PARA3 Standing on the shoulders of giants is not a metaphor in software"
PARA3="$PARA3 — it is a daily reality. My code will stand on Python, Linux, Git,"
PARA3="$PARA3 and the work of thousands who came before me."

PARA4="Open source is not just a licensing model. It is a statement that knowledge"
PARA4="$PARA4 should be shared, that software should be transparent, and that"
PARA4="$PARA4 the tools that shape the world should belong to the people who use them."

# --- Write manifesto to file using > (overwrite) and >> (append) ---
# First, write the header using > (creates/overwrites the file)
echo "============================================================" > "$OUTPUT"
echo "  MY OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "  Generated by: Shubham Kumar | 24BCG10078" >> "$OUTPUT"
echo "  Date: $DATE" >> "$OUTPUT"
echo "  Software Audited: Python (PSF License)" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Append each paragraph using >>
echo "$PARA1" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$PARA2" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$PARA3" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$PARA4" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Append a closing signature
echo "------------------------------------------------------------" >> "$OUTPUT"
echo "  Signed: Shubham Kumar" >> "$OUTPUT"
echo "  Roll:   24BCG10078" >> "$OUTPUT"
echo "  Date:   $DATE" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"

# --- Confirm and display the saved manifesto ---
echo "------------------------------------------------------------"
echo "  [✔] Manifesto saved to: $OUTPUT"
echo "------------------------------------------------------------"
echo ""

# Display the file contents using cat
cat "$OUTPUT"

echo ""
echo "============================================================"
echo "  Your manifesto has been saved. You can find it at:"
echo "  $(pwd)/$OUTPUT"
echo "============================================================"
